apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f compose/3/docker-compose.yml convert -o gitlab --volumes hostPath --service-group-name gitlab -c
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: gitlab
  name: gitlab
spec:
  ports:
    - name: "2222"
      port: 2222
      targetPort: 22
    - name: "14430"
      port: 14430
      targetPort: 4430
  selector:
    io.kompose.service: gitlab
status:
  loadBalancer: {}
